package com.itio.silowuz.dataclass.exercise

import kotlinx.serialization.Serializable

/**
 * Data class representing a training plan in the application.
 * A training plan consists of a name and a list of exercise IDs that should be performed.
 * Each plan is associated with a specific user via userId for data isolation.
 * 
 * @param id Unique identifier for the training plan (auto-generated by Firebase when new)
 * @param name The human-readable name of the training plan
 * @param exerciseIds List of exercise IDs that are included in this training plan
 * @param userId Identifier of the owner of this training plan
 */
@Serializable
data class TrainingPlan(
    val id: String = "",
    val name: String = "",
    val exerciseIds: List<String> = emptyList(),
    val userId: String = ""
)
